### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by shams3049** [Pi4J/pi4j-example-crowpi#27]
I had the same problem in my project, which has many changes, But I see that the same problem exists on Pi with everything standard as described in the repo main(No changes were made):

Is the upgrade to 17 being tested on the latest image for CrowPi?

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  49.152 s
[INFO] Finished at: 2022-09-18T16:41:08+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project crowpi-examples: Fatal error compiling: error: release version 17 not supported -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by FDelporte** [comment]
What is the Java version you are using to run your application? Can you check `java -version`? This looks like a mismatch between the compilation and runtime version.

**Comment by DieterHolz** [comment]
Make sure to use this image https://pi4j-download.com/crowpi-main.img.zip

On your developer machine you have to use jdk17 as well

**Comment by shams3049** [comment]
@DieterHolz The link from the image resolved the issue. I think the link on the readme.md has to be updated.
